"""Method registry and future module labels."""

FUTURE_MODULES = {
    "Gravity": [
        "Free-air correction",
        "Bouguer correction",
        "Terrain correction",
        "Complete Bouguer anomaly",
        "Isostatic anomaly",
        "Gravity gradient tensor",
    ],
    "Magnetic": [
        "IGRF correction",
        "Diurnal correction",
        "Magnetic anomaly",
        "RTP",
        "RTE",
        "Pseudo-gravity",
        "Susceptibility inversion",
        "Magnetization vector inversion",
    ],
    "Depth Estimation": [
        "Euler deconvolution",
        "3D Euler",
        "Extended Euler",
        "SPI",
        "Werner deconvolution",
        "Naudy method",
        "Peters half-slope method",
        "Tilt-depth",
        "Analytic signal depth",
        "Local wavenumber depth",
        "Matched filtering depth",
        "Spectral centroid",
        "Curie point depth",
    ],
    "Modeling / Inversion": [
        "2D gravity forward modeling",
        "2.5D gravity forward modeling",
        "3D gravity forward modeling",
        "2D magnetic forward modeling",
        "2.5D magnetic forward modeling",
        "3D magnetic forward modeling",
        "Parker-Oldenburg inversion",
        "Occam inversion",
        "Compact inversion",
        "Focusing inversion",
        "Bayesian inversion",
        "Joint gravity-magnetic inversion",
    ],
    "GIS / Interpretation": [
        "Shapefile overlay",
        "Fault overlay",
        "Geological overlay",
        "Automatic lineament extraction",
        "Skeletonization",
        "Hough transform",
        "Rose diagram",
        "Lineament density",
        "Intersection density",
        "Geothermal favorability map",
    ],
}


SCIENTIFIC_WARNINGS = [
    "FFT derivatives, RAPS, upward continuation, and wavelength filters require regular projected coordinates in meters.",
    "Coordinates in degrees should be reprojected to UTM before interpretation.",
    "First vertical derivative enhances shallow sources and noise.",
    "Second vertical derivative strongly amplifies noise.",
    "Upward continuation smooths anomalies and is not a unique geological separation.",
    "Butterworth regional/residual separation depends on cutoff wavelength and filter order.",
    "RAPS depth estimates depend on spectrum convention, windowing, detrending, and selected slope segment.",
    "For a 50 km x 50 km study area, very deep sources may not be reliably resolved.",
    "FFT methods may suffer from boundary artifacts. Use tapering and padding.",
    "Filters highlight mathematical gradients and edges, not automatically faults. Geological validation is required.",
]
